packages: []

catalogs:

  build:
    '@iconify-json/carbon': ^1.2.8
    '@vitejs/plugin-vue': ^5.2.3
    jsdom: ^26.0.0
    unocss: ^66.1.0-beta.7
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.4.1
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.2.3
    vite-plugin-vue-layouts: ^0.11.0

  dev:
    '@types/node': ^22.13.14
    '@unocss/eslint-plugin': ^66.1.0-beta.7
    '@uxuip/eslint-config': ^4.0.0
    '@vue-macros/volar': ^3.0.0-beta.7
    '@vue/test-utils': ^2.4.6
    eslint: ^9.23.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.12.1
    taze: ^19.0.2
    typescript: ^5.8.2
    vitest: ^3.0.9
    vue-tsc: ^2.2.8

  frontend:
    '@vueuse/core': ^13.0.0
    vue: ^3.5.13
    vue-router: ^4.5.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
